"""Instrument metadata only. All valuations are obtained from providers."""
REGIONS = ['World', 'Americas', 'Europe', 'Asia', 'Middle East', 'Africa', 'Australia & Oceania']
ASSETS = []
def add(name, symbol, country, region, exchange, currency, kind='Indexes'):
    ASSETS.append(dict(id=symbol, name=name, symbol=symbol, country=country, region=region, exchange=exchange, currency=currency, type=kind))
for name,symbol,country,region,exchange,currency in [
('S&P 500','^GSPC','United States','Americas','S&P','USD'),('Nasdaq Composite','^IXIC','United States','Americas','NASDAQ','USD'),('Nasdaq-100','^NDX','United States','Americas','NASDAQ','USD'),('Dow Jones','^DJI','United States','Americas','Dow Jones','USD'),('Russell 2000','^RUT','United States','Americas','FTSE Russell','USD'),
('S&P/TSX Composite','^GSPTSE','Canada','Americas','TSX','CAD'),('S&P/TSX 60','^TX60','Canada','Americas','TSX','CAD'),('IBOVESPA','^BVSP','Brazil','Americas','B3','BRL'),('S&P/BMV IPC','^MXX','Mexico','Americas','BMV','MXN'),('MERVAL','^MERV','Argentina','Americas','BYMA','ARS'),('IPSA','^IPSA','Chile','Americas','Santiago','CLP'),
('FTSE 100','^FTSE','United Kingdom','Europe','LSE','GBP'),('FTSE 250','^FTMC','United Kingdom','Europe','LSE','GBP'),('DAX','^GDAXI','Germany','Europe','Xetra','EUR'),('MDAX','^MDAXI','Germany','Europe','Xetra','EUR'),('CAC 40','^FCHI','France','Europe','Euronext Paris','EUR'),('AEX','^AEX','Netherlands','Europe','Euronext Amsterdam','EUR'),('BEL 20','^BFX','Belgium','Europe','Euronext Brussels','EUR'),('PSI','PSI20.LS','Portugal','Europe','Euronext Lisbon','EUR'),('IBEX 35','^IBEX','Spain','Europe','Madrid','EUR'),('FTSE MIB','FTSEMIB.MI','Italy','Europe','Borsa Italiana','EUR'),('SMI','^SSMI','Switzerland','Europe','SIX','CHF'),('OMX Stockholm 30','^OMX','Sweden','Europe','Nasdaq Stockholm','SEK'),('OMX Copenhagen 25','^OMXC25','Denmark','Europe','Nasdaq Copenhagen','DKK'),('OMX Helsinki 25','^OMXH25','Finland','Europe','Nasdaq Helsinki','EUR'),('OBX','OBX.OL','Norway','Europe','Oslo','NOK'),('ATX','^ATX','Austria','Europe','Vienna','EUR'),('ISEQ','^ISEQ','Ireland','Europe','Euronext Dublin','EUR'),('WIG20','WIG20.WA','Poland','Europe','Warsaw','PLN'),('BET','BET.RO','Romania','Europe','Bucharest','RON'),('EURO STOXX 50','^STOXX50E','Europe','Europe','STOXX','EUR'),('STOXX Europe 600','^STOXX','Europe','Europe','STOXX','EUR'),
('Shanghai Composite','000001.SS','China','Asia','Shanghai','CNY'),('CSI 300','000300.SS','China','Asia','Shanghai / Shenzhen','CNY'),('Shenzhen Component','399001.SZ','China','Asia','Shenzhen','CNY'),('Hang Seng','^HSI','Hong Kong','Asia','HKEX','HKD'),('Hang Seng TECH','HSTECH.HK','Hong Kong','Asia','HKEX','HKD'),('Nikkei 225','^N225','Japan','Asia','Tokyo','JPY'),('TOPIX','^TOPX','Japan','Asia','Tokyo','JPY'),('KOSPI','^KS11','South Korea','Asia','KRX','KRW'),('KOSDAQ','^KQ11','South Korea','Asia','KRX','KRW'),('NIFTY 50','^NSEI','India','Asia','NSE','INR'),('NIFTY Bank','^NSEBANK','India','Asia','NSE','INR'),('BSE SENSEX','^BSESN','India','Asia','BSE','INR'),('TAIEX','^TWII','Taiwan','Asia','TWSE','TWD'),('Straits Times','^STI','Singapore','Asia','SGX','SGD'),('Jakarta Composite','^JKSE','Indonesia','Asia','IDX','IDR'),('FTSE Bursa Malaysia KLCI','^KLSE','Malaysia','Asia','Bursa Malaysia','MYR'),('SET Index','^SET.BK','Thailand','Asia','SET','THB'),('PSEi','PSEI.PS','Philippines','Asia','PSE','PHP'),('VN-Index','^VNINDEX.VN','Vietnam','Asia','HOSE','VND'),('KSE 100','^KSE','Pakistan','Asia','PSX','PKR'),('DSEX','DSEX','Bangladesh','Asia','Dhaka','BDT'),('ASPI','^CSE','Sri Lanka','Asia','Colombo','LKR'),('NEPSE','NEPSE','Nepal','Asia','NEPSE','NPR'),
('S&P/ASX 200','^AXJO','Australia','Australia & Oceania','ASX','AUD'),('All Ordinaries','^AORD','Australia','Australia & Oceania','ASX','AUD'),('S&P/NZX 50','^NZ50','New Zealand','Australia & Oceania','NZX','NZD'),
('TASI','^TASI.SR','Saudi Arabia','Middle East','Tadawul','SAR'),('ADX General','^ADI','United Arab Emirates','Middle East','ADX','AED'),('DFM General','DFMGI.AE','United Arab Emirates','Middle East','DFM','AED'),('TA-35','^TA35.TA','Israel','Middle East','Tel Aviv','ILS'),('BIST 100','XU100.IS','Turkey','Middle East','Borsa Istanbul','TRY'),('QE Index','DSM.QA','Qatar','Middle East','Qatar','QAR'),
('FTSE/JSE Top 40','^J200.JO','South Africa','Africa','JSE','ZAR'),('EGX 30','^CASE30','Egypt','Africa','Egyptian Exchange','EGP'),('NGX All Share','NGXASI','Nigeria','Africa','NGX','NGN'),('NSE 20','NSE20','Kenya','Africa','Nairobi','KES'),('MASI','MASI','Morocco','Africa','Casablanca','MAD')]: add(name,symbol,country,region,exchange,currency)
for name,symbol,kind,exchange in [('Apple','AAPL','Stocks','NASDAQ'),('Microsoft','MSFT','Stocks','NASDAQ'),('NVIDIA','NVDA','Stocks','NASDAQ'),('Amazon','AMZN','Stocks','NASDAQ'),('Alphabet','GOOGL','Stocks','NASDAQ'),('Tesla','TSLA','Stocks','NASDAQ'),('SPDR S&P 500 ETF','SPY','ETFs','NYSE Arca'),('Vanguard Total Stock Market','VTI','ETFs','NYSE Arca'),('Invesco QQQ','QQQ','ETFs','NASDAQ')]: add(name,symbol,'United States','Americas',exchange,'USD',kind)
for name,symbol in [('Gold','GC=F'),('Silver','SI=F'),('Copper','HG=F'),('Platinum','PL=F'),('Palladium','PA=F'),('WTI Crude Oil','CL=F'),('Brent Crude','BZ=F'),('Natural Gas','NG=F'),('Wheat','ZW=F'),('Corn','ZC=F'),('Soybeans','ZS=F'),('Coffee','KC=F'),('Sugar','SB=F'),('Cotton','CT=F')]: add(name,symbol,'Global','World','Futures benchmark','USD','Commodities')
for symbol in ['EURUSD','GBPUSD','USDJPY','USDCHF','AUDUSD','USDCAD','NZDUSD','USDCNY','USDINR','EURGBP','EURJPY','GBPJPY']: add(symbol[:3]+'/'+symbol[3:],symbol+'=X','Global','World','FX',symbol[3:],'Forex')
