import React,{useEffect,useState} from 'react';
import {SafeAreaView,View,Text,TextInput,ScrollView,Pressable,StyleSheet,Platform,Share,Linking} from 'react-native';
import * as SecureStore from 'expo-secure-store';
import {StatusBar} from 'expo-status-bar';
import {createFinancialClient,DESIGN_TOKENS as tokens,SCREEN_IDS} from '../static/shared/financial-api.js';
const API_URL=process.env.EXPO_PUBLIC_API_URL||(Platform.OS==='android'?'http://10.0.2.2:3000':'http://localhost:3000');
const vault={get:()=>Platform.OS==='web'?Promise.resolve(sessionStorage.getItem('sharebajar-session')||''):SecureStore.getItemAsync('sharebajar-session'),set:token=>Platform.OS==='web'?Promise.resolve(token?sessionStorage.setItem('sharebajar-session',token):sessionStorage.removeItem('sharebajar-session')):token?SecureStore.setItemAsync('sharebajar-session',token):SecureStore.deleteItemAsync('sharebajar-session')};
const api=createFinancialClient({baseUrl:API_URL,getToken:vault.get});
const PRIVATE=new Set(['watchlist','portfolio-import','portfolio','ai-chat','forecast','alerts','saved-reports','profile']);
const cash=(n,c)=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(n);
const names={'onboarding':'Welcome','choose-market':'Choose market','home':'Market dashboard','search':'Search assets','rankings':'Rankings','asset-detail':'Asset research','watchlist':'Watchlist','portfolio-import':'Portfolio import','portfolio':'Portfolio overview','ai-chat':'AI research','forecast':'Forecast scenarios','alerts':'Alerts','saved-reports':'Saved reports','pricing':'Research plans','profile':'Profile & settings'};
const Button=({children,onPress,secondary=false,disabled=false})=><Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.button,secondary&&s.secondary,disabled&&{opacity:.5}]}><Text style={[s.buttonText,secondary&&{color:tokens.ink}]}>{children}</Text></Pressable>;
const Card=({children})=><View style={s.card}>{children}</View>;
const Heading=({children})=><Text style={s.h2}>{children}</Text>;
const Body=({children})=><Text style={s.body}>{children}</Text>;
const Field=({label,...props})=><View style={{marginVertical:8}}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} style={[s.input,props.multiline&&{minHeight:100,textAlignVertical:'top'}]} placeholderTextColor="#899485" {...props}/></View>;
export default function App(){
 const [screen,setScreen]=useState('onboarding'),[markets,setMarkets]=useState([]),[market,setMarket]=useState('us'),[suggestion,setSuggestion]=useState(null),[data,setData]=useState(null),[workspace,setWorkspace]=useState(null),[account,setAccount]=useState(null),[asset,setAsset]=useState(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[menu,setMenu]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[signup,setSignup]=useState(false),[csv,setCsv]=useState('marketCode,symbol,quantity,costBasis\nus,AAPL,10,180\nus,MSFT,5,400'),[prompt,setPrompt]=useState('Review valuation context and the risks to verify.'),[template,setTemplate]=useState('asset-research'),[threshold,setThreshold]=useState(''),[direction,setDirection]=useState('above');
 useEffect(()=>{api.markets().then(rows=>{setMarkets(rows);try{const region=new Intl.Locale(Intl.DateTimeFormat().resolvedOptions().locale).region;setSuggestion(rows.find(m=>m.isoCountry===region)||null)}catch{}}).catch(e=>setStatus(e.message));(Platform.OS==='web'?Promise.resolve(localStorage.getItem('sharebajar-market')):SecureStore.getItemAsync('sharebajar-market')).then(code=>{if(code)setMarket(code)}).catch(()=>{});refreshAccount();},[]);
 useEffect(()=>{setBusy(true);api.valuation(market,filter).then(x=>{setData(x);setAsset(a=>a?.marketCode===market?a:x.assets[0]||null)}).catch(e=>setStatus(e.message)).finally(()=>setBusy(false));},[market,filter]);
 async function refreshAccount(){try{const a=await api.account();const nextWorkspace=a.signedIn?await api.workspace():null;setWorkspace(nextWorkspace);setAccount(a)}catch(e){setStatus(e.message)}}
 async function act(body){setBusy(true);try{const result=await api.action(body);setWorkspace(result.state);setStatus(result.message)}catch(e){setStatus(e.message)}finally{setBusy(false)}}
 async function authenticate(){setBusy(true);try{const r=await api.authenticate(signup?'signup':'login',{email,password});await vault.set(r.token);setPassword('');await refreshAccount();setStatus('Signed in. Your account is shared with the web app.')}catch(e){setStatus(e.message)}finally{setBusy(false)}}
 function navigate(next){setScreen(next);setStatus('');setMenu(false)}
 function choose(code){if(Platform.OS==='web')localStorage.setItem('sharebajar-market',code);else SecureStore.setItemAsync('sharebajar-market',code).catch(()=>{});setMarket(code);setFilter('all');navigate('home')}
 function assetRows(rows){return rows.map(a=><Pressable accessibilityRole="button" key={a.marketCode+':'+a.symbol} onPress={()=>{if(!a.assetUrl){api.valuation(a.marketCode).then(x=>{setAsset(x.assets.find(v=>v.symbol===a.symbol)||a);navigate('asset-detail')}).catch(e=>setStatus(e.message))}else{setAsset(a);navigate('asset-detail')}}} style={s.assetRow}><View style={{flex:1}}><Text style={s.strong}>{a.name}</Text><Text style={s.small}>{a.symbol} · {a.exchange}</Text><Text style={s.small}>{a.valuationLabel||'Mock price snapshot'}</Text></View><View><Text style={s.strong}>{cash(a.price,a.currency)}</Text><Text style={[s.small,{color:a.changes['1d']>=0?'#288819':'#b44332'}]}>{a.changes['1d']}%</Text></View></Pressable>)}
 function gate(plan='plus'){return <Card><Heading>Expand your research workflow</Heading><Body>{plan==='pro'?'Pro includes forecasts, multiple portfolios and exports.':'Plus includes portfolio import, analysis, saved research and alerts.'}</Body><Button onPress={()=>navigate('pricing')}>Explore {plan.toUpperCase()}</Button></Card>}
 const m=markets.find(x=>x.marketCode===market),paid=workspace?.permissions.portfolioImport;
 let body;
 if(PRIVATE.has(screen)&&!account?.signedIn)body=<Card><Heading>Make it your research workspace</Heading><Body>Sign in to save assets and access your account across web, iOS and Android.</Body><Field label="Email" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" autoComplete="email"/><Field label="Password (12–128 characters)" value={password} onChangeText={setPassword} secureTextEntry autoComplete={signup?'new-password':'current-password'}/><Button disabled={busy} onPress={authenticate}>{signup?'Create account':'Sign in'}</Button><Button secondary onPress={()=>setSignup(!signup)}>{signup?'I already have an account':'Create a free account'}</Button></Card>;
 else if(PRIVATE.has(screen)&&!workspace)body=<Card><Body>Opening your account workspace…</Body></Card>;
 else if(screen==='onboarding')body=<><Text style={s.hero}>Understand markets.{ '\n' }Grow with insight.</Text><Body>Valuation research, portfolio analysis and AI-assisted financial experiences, together.</Body><Card><Heading>Start with the market</Heading><Body>Explore 18 markets. Compare assets. Build a thesis before you import your holdings.</Body></Card><Button onPress={()=>navigate('choose-market')}>Get started →</Button><Button secondary onPress={()=>navigate('home')}>Explore public markets</Button></>;
 else if(screen==='choose-market')body=<><Body>Your location can suggest a market. You can change it anytime.</Body>{suggestion&&<Button secondary onPress={()=>choose(suggestion.marketCode)}>Suggested: {suggestion.countryName}</Button>}<Field label="Search markets" value={query} onChangeText={setQuery}/>{markets.filter(x=>(x.countryName+' '+x.marketCode).toLowerCase().includes(query.toLowerCase())).map(x=><Button secondary key={x.marketCode} onPress={()=>choose(x.marketCode)}>{x.flag} {x.countryName} · {x.currency}</Button>)}</>;
 else if(['home','rankings','search'].includes(screen))body=<>{screen==='search'&&<Field label="Search this market" value={query} onChangeText={setQuery} placeholder="Apple, Bitcoin, NABIL"/>}{screen!=='search'&&data&&<Card><Heading>{m?.countryName} market lens</Heading><Text style={s.metric}>{data.overview.valuationScore??'—'}<Text style={s.small}> /100 relative valuation</Text></Text><Body>{data.overview.summary}</Body></Card>}<ScrollView horizontal showsHorizontalScrollIndicator={false}>{['all','undervalued','fair','overvalued','dividend','growth'].map(v=><Pressable key={v} onPress={()=>setFilter(v)} style={[s.chip,filter===v&&{background:tokens.soft,borderColor:tokens.accent}]}><Text style={s.small}>{v}</Text></Pressable>)}</ScrollView><Card>{assetRows((data?.assets||[]).filter(a=>screen!=='search'||(a.name+' '+a.symbol).toLowerCase().includes(query.toLowerCase())))}</Card><Button secondary onPress={()=>Linking.openURL(API_URL+'/research')}>Explore public research pages →</Button></>;
 else if(screen==='asset-detail')body=asset?<><Card><Text style={s.small}>{asset.symbol} · {asset.exchange}</Text><Heading>{asset.name}</Heading><Text style={s.metric}>{cash(asset.price,asset.currency)}</Text><Body>{asset.valuationLabel}</Body><Body>{asset.valuationRationale}</Body><View style={s.metrics}>{[['P/E',asset.pe],['P/B',asset.pb],['Yield',asset.dividendYield],['Score',asset.valuationScore]].map(([k,v])=><View key={k} style={{width:'48%',padding:10}}><Text style={s.small}>{k}</Text><Text style={s.strong}>{v??'Not applicable'}</Text></View>)}</View><Body>{asset.valuationMethodology}</Body><Button onPress={()=>account?.signedIn?act({action:'watch_add',marketCode:asset.marketCode,symbol:asset.symbol}):navigate('watchlist')}>☆ Save to watchlist</Button><Button secondary onPress={()=>navigate('ai-chat')}>Research this asset ✦</Button></Card><Button secondary onPress={()=>Linking.openURL(API_URL+asset.assetUrl)}>Full asset research page →</Button></>:<Body>Choose an asset from rankings.</Body>;
 else if(screen==='watchlist')body=<><Card>{assetRows(workspace.watchlist)}{!workspace.watchlist.length&&<Body>Your watchlist starts with an asset research page.</Body>}</Card><Button onPress={()=>navigate('rankings')}>Discover assets →</Button>{workspace.watchlist.map(a=><Button key={a.marketCode+a.symbol} secondary onPress={()=>act({action:'watch_remove',marketCode:a.marketCode,symbol:a.symbol})}>Remove {a.symbol}</Button>)}</>;
 else if(screen==='portfolio-import')body=!paid?gate():<Card><Heading>Import recorded holdings</Heading><Body>CSV headers: marketCode,symbol,quantity,costBasis. Mock prices value your recorded quantities. No broker connection is active.</Body><Field label="Holdings CSV" multiline value={csv} onChangeText={setCsv}/><Button disabled={busy} onPress={()=>act({action:'portfolio_import',name:'Mobile portfolio',csv,...(workspace.portfolios[0]?{portfolioId:workspace.portfolios[0].id}:{})})}>Import holdings</Button><Button secondary disabled={busy} onPress={()=>act({action:'demo_sync',name:'Demo portfolio',marketCode:market,...(workspace.portfolios[0]?{portfolioId:workspace.portfolios[0].id}:{})})}>Sync demo portfolio</Button></Card>;
 else if(screen==='portfolio')body=!paid?gate():<><Button onPress={()=>navigate('portfolio-import')}>Import or update portfolio</Button>{workspace.portfolios.map(p=><Card key={p.id}><Heading>{p.name}</Heading>{Object.entries(p.totalsByCurrency).map(([c,v])=><View key={c}><Text style={s.metric}>{cash(v.value,c)}</Text><Body>{cash(v.gain,c)} unrealized gain · values grouped by currency</Body></View>)}{p.holdings.map(h=><Body key={h.marketCode+h.symbol}>{h.symbol} · {h.quantity} units · {cash(h.marketValue,h.currency)}</Body>)}<Heading>Concentration analysis</Heading>{p.risk.byCurrency.map(r=><Body key={r.currency}>{r.currency}: {r.largestPositionPercent}% largest position · {r.concentrationLabel} concentration</Body>)}<Body>{p.risk.method}</Body><Button secondary onPress={()=>navigate('forecast')}>Explore scenarios</Button></Card>)}</>;
 else if(screen==='ai-chat')body=!paid?gate():<Card><Heading>Frame a better research question</Heading><Body>Structured mock research uses your selected asset or first portfolio. Live AI reports are available on the web when configured.</Body><Field label="Research question" value={prompt} onChangeText={setPrompt} multiline maxLength={1000}/><ScrollView horizontal>{workspace.templates.map(t=><Pressable key={t.id} style={s.chip} onPress={()=>setTemplate(t.id)}><Text style={s.small}>{template===t.id?'✓ ':''}{t.name} · {t.plan}</Text></Pressable>)}</ScrollView><Body>Selected asset: {asset?.name||'Choose one from rankings'}</Body><Button disabled={busy} onPress={()=>act({action:'report_generate',template,title:'Mobile research report',prompt,marketCode:asset?.marketCode||market,symbol:asset?.symbol,portfolioId:workspace.portfolios[0]?.id})}>Generate & save research ✦</Button><Button secondary onPress={()=>navigate('saved-reports')}>Open research library</Button></Card>;
 else if(screen==='forecast')body=!workspace.permissions.forecast?gate('pro'):<><Body>Illustrative assumptions, not predictions or probability estimates.</Body>{workspace.scenarios.map(p=><Card key={p.portfolioId}><Heading>{workspace.portfolios.find(x=>x.id===p.portfolioId)?.name}</Heading><Body>{p.method}</Body>{p.byCurrency.map(c=><View key={c.currency}><Heading>{c.currency} · {p.horizon}</Heading>{c.scenarios.map(x=><Body key={x.name}>{x.name}: {cash(x.value,c.currency)} · {x.changePercent}% assumed change</Body>)}</View>)}</Card>)}{!workspace.scenarios.length&&<Button onPress={()=>navigate('portfolio-import')}>Import a portfolio</Button>}</>;
 else if(screen==='alerts')body=!workspace.permissions.alerts?gate():<><Card><Heading>Price threshold for {asset?.symbol||'selected asset'}</Heading><Body>In-app snapshot alerts only. No external push or email delivery is connected.</Body><Field label="Threshold price" value={threshold} onChangeText={setThreshold} keyboardType="decimal-pad"/><Button secondary onPress={()=>setDirection(direction==='above'?'below':'above')}>Condition: {direction}</Button><Button disabled={busy||!asset} onPress={()=>act({action:'alert_create',marketCode:asset?.marketCode,symbol:asset?.symbol,direction,threshold})}>Create alert</Button></Card>{workspace.alerts.map(a=><Card key={a.id}><Heading>{a.asset.name}</Heading><Body>{a.direction} {cash(a.threshold,a.asset.currency)} · {a.status}</Body><Button secondary onPress={()=>act({action:'alert_remove',id:a.id})}>Remove alert</Button></Card>)}</>;
 else if(screen==='saved-reports')body=!workspace.permissions.savedReports?gate():<>{workspace.reports.map(r=><Card key={r.id}><Heading>{r.title}</Heading><Body>{r.content.question}</Body>{r.content.sections.map((x,i)=><View key={i}><Text style={s.strong}>{x.heading}</Text><Body>{x.body}</Body></View>)}<Body>{r.content.limitations}</Body>{workspace.permissions.export&&<Button secondary onPress={async()=>{try{const x=await api.request('growth/export?id='+r.id);await Share.share({message:x.content,title:r.title})}catch(e){setStatus(e.message)}}}>Export / share report</Button>}<Button secondary onPress={()=>act({action:'report_delete',id:r.id})}>Delete report</Button></Card>)}{!workspace.reports.length&&<Button onPress={()=>navigate('ai-chat')}>Create your first report</Button>}</>;
 else if(screen==='pricing')body=[{name:'Free',price:0,features:'Public rankings, basic asset research, basic watchlist'},{name:'Plus',price:19,features:'AI research, portfolio analysis, saved reports, advanced rankings'},{name:'Pro',price:99,features:'Forecast scenarios, advanced templates, multiple portfolios, exports, priority data refresh'}].map(p=><Card key={p.name}><Heading>{p.name}</Heading><Text style={s.metric}>$ {p.price}<Text style={s.small}> / month</Text></Text><Body>{p.features}</Body><Button onPress={()=>p.name==='Free'?navigate('watchlist'):Linking.openURL(API_URL+'/pricing')}>{p.name==='Free'?'Create free account':'Explore '+p.name}</Button><Body>Paid checkout and live refresh depend on server configuration.</Body></Card>);
 else if(screen==='profile')body=<Card><Heading>{account.email}</Heading><Body>{account.plan.toUpperCase()} account · one account across devices</Body><Body>Home market: {workspace.preferences.marketCode.toUpperCase()}</Body><Button secondary onPress={()=>act({action:'profile_update',marketCode:market,riskProfile:workspace.preferences.riskProfile,horizon:workspace.preferences.horizon})}>Use {m?.countryName} as my home market</Button><Button secondary onPress={()=>act({action:'profile_update',marketCode:workspace.preferences.marketCode,riskProfile:workspace.preferences.riskProfile==='balanced'?'conservative':'balanced',horizon:workspace.preferences.horizon})}>Research style: {workspace.preferences.riskProfile}</Button><Button secondary onPress={()=>act({action:'profile_update',marketCode:workspace.preferences.marketCode,riskProfile:workspace.preferences.riskProfile,horizon:workspace.preferences.horizon==='long-term'?'short-term':'long-term'})}>Horizon: {workspace.preferences.horizon}</Button><Button secondary onPress={async()=>{try{await api.request('auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await vault.set('');setAccount(null);setWorkspace(null);navigate('home')}catch(e){setStatus(e.message)}}}>Sign out</Button></Card>;
 return <SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={s.header}><Pressable accessibilityRole="button" onPress={()=>navigate('home')}><Text style={s.brand}>↗ sharebajar.</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>navigate('choose-market')}><Text style={s.small}>{m?.flag} {m?.countryName||market.toUpperCase()} ▾</Text></Pressable></View><View style={s.screenHeading}><Text style={s.h2}>{names[screen]}</Text><Pressable accessibilityRole="button" onPress={()=>setMenu(!menu)}><Text style={s.small}>All screens ☰</Text></Pressable></View>{menu&&<ScrollView style={{maxHeight:220}}><View style={s.menu}>{SCREEN_IDS.map(x=><Pressable key={x} accessibilityRole="button" style={s.chip} onPress={()=>navigate(x)}><Text style={s.small}>{names[x]}</Text></Pressable>)}</View></ScrollView>}<ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.notice}>MOCK DATA · Illustrative prices, valuation and structured research</Text>{status&&<Text accessibilityRole="alert" style={s.notice}>{status}</Text>}{busy&&<Text style={s.small}>Loading…</Text>}{body}</ScrollView><View style={s.bottom}>{[['home','Markets'],['ai-chat','Research'],['watchlist','Watchlist'],['portfolio','Portfolio']].map(([id,label])=><Pressable key={id} accessibilityRole="button" onPress={()=>navigate(id)}><Text style={[s.small,screen===id&&{color:tokens.accent,fontWeight:'700'}]}>{label}</Text></Pressable>)}</View></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:tokens.background},header:{padding:16,borderBottomWidth:1,borderColor:tokens.line,flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:8},brand:{fontSize:22,fontWeight:'700',color:tokens.ink},screenHeading:{padding:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},content:{padding:16,paddingBottom:35,maxWidth:720,width:'100%',alignSelf:'center'},hero:{fontSize:38,fontWeight:'700',lineHeight:45,color:tokens.ink,letterSpacing:-1.5,marginVertical:20},h2:{fontSize:21,fontWeight:'700',color:tokens.ink,marginVertical:8,flexShrink:1},body:{fontSize:13,lineHeight:22,color:tokens.muted,marginVertical:8},small:{fontSize:11,lineHeight:18,color:tokens.muted},strong:{fontSize:13,color:tokens.ink,fontWeight:'600',lineHeight:21},card:{borderWidth:1,borderColor:tokens.line,borderRadius:tokens.radius,padding:18,marginVertical:10,backgroundColor:'#fff'},button:{backgroundColor:tokens.accent,borderRadius:7,padding:13,marginVertical:8,alignItems:'center'},secondary:{backgroundColor:'#fff',borderWidth:1,borderColor:tokens.line},buttonText:{fontSize:13,fontWeight:'600',color:'#fff'},label:{fontSize:11,color:tokens.muted,marginBottom:8},input:{padding:12,borderWidth:1,borderColor:tokens.line,borderRadius:7,color:tokens.ink,backgroundColor:'#fff',fontSize:13},metric:{fontSize:30,fontWeight:'700',color:tokens.ink,marginVertical:12},metrics:{flexDirection:'row',flexWrap:'wrap',gap:5},assetRow:{flexDirection:'row',gap:12,borderBottomWidth:1,borderColor:tokens.line,paddingVertical:15},chip:{paddingHorizontal:12,paddingVertical:9,margin:4,borderWidth:1,borderColor:tokens.line,borderRadius:6},notice:{padding:12,borderWidth:1,borderColor:tokens.line,borderRadius:7,backgroundColor:tokens.soft,fontSize:10,lineHeight:17,color:tokens.muted,marginBottom:15},bottom:{flexDirection:'row',justifyContent:'space-around',borderTopWidth:1,borderColor:tokens.line,padding:17,backgroundColor:'#fff'},menu:{flexDirection:'row',flexWrap:'wrap',paddingHorizontal:12}});
